# Wayland & Input Method Environments
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
SDL_IM_MODULE=fcitx
WEBKIT_DISABLE_DMABUF_RENDERER=1
XCURSOR_SIZE=24
QT_QPA_PLATFORM="wayland;xcb"
MOZ_ENABLE_WAYLAND=1
